---

- name: backup plexdata 
  archive:
    path: '{{ local_path }}/plexdata'
    dest: '{{ backup_path }}/plexdata.xz'
    format: xz

- name: backup nginx
  archive:
    path: '{{ local_path }}/etc/nginx'
    dest: '{{ backup_path }}/nginx.xz'
    format: xz

- name: backup pf_files
  archive:
    path: /etc/pf-files
    dest: '{{ backup_path }}/pf-files.xz'
    format: xz

- name: backup letsencrypt
  archive:
    path: '{{ local_path }}/etc/letsencrypt'
    dest: '{{ backup_path }}/letsencrypt.xz'
    format: xz
