---
# tasks file for role_freebsd

- name: check if {{ packages | to_yaml }} are installed
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
  when: ansible_distribution == "FreeBSD"

