---
# tasks file for role_freebsd

#- include: display_ip.yml
#- include: service.yml
- include: install.yml
- include: backup.yml

- name: sshd_config file
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: restart sshd

- name: plexupdate script
  template:
    src: plexupdate.j2
    dest: '{{ local_bin }}/plexupdate'
    owner: '{{ owner }}'
    mode: 0755

- name: plexmediaserver service
  template:
    src: plexmediaserver.j2
    dest: '{{ local_path }}/etc/rc.d/plexmediaserver'
    owner: root
    group: wheel
    mode: 0755

- name: file '{{ local_path }}/etc/nginx/nginx.conf'
  template:
    src: nginx.conf.j2
    dest: '{{ local_path }}/etc/nginx/nginx.conf'
    owner: root
    group: wheel
  notify: restart nginx

- name: file '{{ local_path }}/etc/smb4.conf'
  template:
    src: smb4.conf.j2
    dest: '{{ local_path }}/etc/smb4.conf'
    owner: root
    group: wheel
  notify: restart samba

- name: file /var/unbound/unbound.conf
  template:
    src: unbound.conf.j2
    dest: /var/unbound.conf
  notify: restart local_unbound

- name: file /var/unbound/lan-zones.conf
  template: 
    src: lan-zones.conf.j2
    dest: /var/unbound/lan-zones.conf
  notify: restart local_unbound

- name: file /var/unbound/forward.conf
  template:
    src: forward.conf.j2
    dest: /var/unbound/forward.conf
  notify: restart local_unbound

- name: file /boot/loader.conf
  template:
    src: loader.conf.j2
    dest: /boot/loader.conf

- name: file /etc/rc.conf
  template:
    src: rc.conf.j2
    dest: /etc/rc.conf

- name: file /etc/pf.conf
  template:
    src: pf.conf.j2
    dest: /etc/pf.conf
