---
# tasks file for role_freebsd

- include: display_ip.yml
- include: install.yml
- include: service.yml

- name: sshd_config file
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: restart sshd

- name: plexupdate script
  template:
    src: plexupdate.j2
    dest: "{{ local_bin }}/plexupdate"
    owner: "{{ owner }}"
    mode: 0755

- name: vape script
  template:
    src: vape.j2
    dest: "{{ local_bin }}/vape"
    owner: "{{ owner }}"
    mode: 0755

#- name: file /usr/local/etc/afp.conf
#  template:
#    src: afp.conf.j2
#    dest: /usr/local/etc/afp.conf

- name: file /usr/local/etc/nginx/nginx.conf
  template:
    src: nginx.conf.j2
    dest: /usr/local/etc/nginx/nginx.conf
    owner: root
    group: wheel
  notify: restart nginx

#- name: file /usr/local/etc/minidlna.conf
#  template:
#    src: minidlna.conf.j2
#    dest: /usr/local/etc/minidlna.conf
#    owner: root
#    group: wheel

- name: file /usr/local/etc/smb4.conf
  template:
    src: smb4.conf.j2
    dest: /usr/local/etc/smb4.conf
    owner: root
    group: wheel
  notify: restart samba
