---
# tasks file for role_freebsd

#- include: display_ip.yml
#- include: service.yml
- include: install.yml

- name: sshd_config file
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: restart sshd

- name: plexupdate script
  template:
    src: plexupdate.j2
    dest: "{{ local_bin }}/plexupdate"
    owner: "{{ owner }}"
    mode: 0755

- name: file /usr/local/etc/nginx/nginx.conf
  template:
    src: nginx.conf.j2
    dest: /usr/local/etc/nginx/nginx.conf
    owner: root
    group: wheel
  notify: restart nginx

- name: file /usr/local/etc/smb4.conf
  template:
    src: smb4.conf.j2
    dest: /usr/local/etc/smb4.conf
    owner: root
    group: wheel
  notify: restart samba

- name: file /var/unbound/unbound.conf
  template:
    src: unbound.conf.j2
    dest: /var/unbound.conf
  notify: restart local_unbound

- name: file /var/unbound/lan-zones.conf
    src: lan-zones.conf.j2
    dest: /var/unbound/lan-zones.conf
  notify: restart local_unbound

- name: file /var/unbound/forward.conf
    src: forward.conf.j2
    dest: /var/unbound/forward.conf
  notify: restart local_unbound
